### ISSUE TITLE
E2E Testing : Setup Test bed for integration tests and integrate with PROW

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/sig-release#11]
We need to setup the test bed for integration and system tests and integrate with Prow so that they can be automatically run as part of the pipeline. This involves multiple tasks. Following are some of the identified tasks and will be triaged further.  

## Todo 
- [x] nephio-project/sig-release#12
- [x] nephio-project/sig-release#13
- [x] nephio-project/sig-release#14
- [x] nephio-project/sig-release#15

**Comment by aravind254** [comment]
We have requested SIG-2 to clarify the requirements for E2E test bed, https://github.com/nephio-project/sig-release/issues/21

At a high level we need test bed that can a) Run in a local sandboxed environment b) can integrate with Nephio CI/CD (PROW) pipeline.

**Comment by johnbelamaric** [comment]
Let's consider this done once https://github.com/nephio-project/test-infra/pull/65 merges
